# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app
# - Uses /srv/ mount point for /data/ volume


version: '2.1'

volumes:
  nginx:

services:

  app:
    build: hyrax
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis
    volumes:
      - app:/data/tmp/uploads
      - /srv/ngdr/data/:/data/data
    networks:
      internal:

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
    ports:
      - 81:80
      #- 443:443
    networks:
      internal:
