# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app

version: '3'

volumes:
  letsencrypt:

services:

  app:
    volumes:
      - /mnt/ngdr/:/mnt/ngdr

  nginx:
    build: docker/nginx
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
