# Overrides the docker-compose file for production environment
# - app accessible on port 3000

version: '3'

services:
  app: &app
    build:
      args:
        FLUENTD_URL: ${FLUENTD_URL}

  web:
    <<: *app
    ports:
      - 3000:3000

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      internal:
    environment:
      - FLUENTD_HOST=${FLUENTD_HOST}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
