# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app

version: '3'

volumes:
  letsencrypt:

services:

  app:
    volumes:
      - /mnt/ngdr/:/mnt/ngdr

  nginx:
    build: docker/nginx
    depends_on:
      - web
    volumes:
      - letsencrypt:/etc/letsencrypt
    command: sh -c "sed -i '1i daemon off;' /etc/nginx/nginx.conf && certbot --nginx --redirect -d ngdrdemo.cottagelabs.com -n --agree-tos --test-cert --email sysadmin+ngdr@cottagelabs.com"
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
