# Overrides the docker-compose file for production environment
# - app accessible on port 3000

version: '3'

services:
  app: &app
    build:
      args:

  web:
    <<: *app
    ports:
      - 3000:3000

  workers:
    <<: *app
