# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app
# - Production env file for the app

version: '3'

volumes:
  nginx:
  letsencrypt:

services:

  app:
    volumes:
      - /mnt/ngdr/:/mnt/ngdr

  nginx:
    build: docker/nginx
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
