# Overrides the docker-compose file for production environment
# - app accessible on port 3000

version: '3'

services:
  app: &app
    build:
      args:
        FLUENTD_URL: ${FLUENTD_URL}

  web:
    ports:
      - 3000:3000
