terms:
- id: experiments
  term: experiments/実験
  active: true
- id: informatics and data science
  term: informatics and data science/情報・データ科学
  active: true
- id: other
  term: other/その他
  active: true
- id: simulations
  term: simulations/シミュレーション
  active: true
- id: theory
  term: theory/理論
  active: true
