terms:
  - id: http://purl.org/dc/terms/dateAccepted
    term: Accepted
    active: true
  - id: Available
    term: Available (Embargo release)
    active: true
  - id: http://bibframe.org/vocab/copyrightDate
    term: Copyrighted
    active: true
  - id: Collected
    term: Collected
    active: true
  - id: http://purl.org/dc/terms/created
    term: Created
    active: true
  - id: Deposited
    term: Deposited
    active: true
  - id: http://bibframe.org/vocab/providerDate
    term: Submitted
    active: true
  - id: http://bibframe.org/vocab/changeDate
    term: Updated
    active: true
  - id: Registered
    term: Registered
    active: true
