terms:
  - id: http://purl.org/dc/terms/dateAccepted
    term: Accepted
    active: true
  - id: Available
    term: Available
    active: true
  - id: http://bibframe.org/vocab/copyrightDate
    term: Copyrighted
    active: true
  - id: Collected
    term: Collected
    active: true
  - id: http://purl.org/dc/terms/created
    term: Created
    active: true
  - id: Deposited
    term: Deposited
    active: true
  - id: http://purl.org/dc/terms/issued
    term: Issued
    active: true
  - id: Published
    term: Published
    active: true
  - id: http://bibframe.org/vocab/providerDate
    term: Submitted
    active: true
  - id: http://bibframe.org/vocab/changeDate
    term: Updated
    active: true
  - id: http://purl.org/dc/terms/valid
    term: Valid
    active: true
  - id: Processed
    term: Processed
    active: true
  - id: Purchased
    term: Purchased
    active: true
  - id: Registered
    term: Registered
    active: true
