terms:
  - id: identifier local
    term: Identifier - Local
    active: true
  - id: identifier persistent
    term: Identifier - Persistent
    active: true
  - id: DOI
    term: DOI
    active: true
  - id: edu person principal name
    term: eduPersonPrincipalName
    active: true
  - id: edu person targeted id
    term: eduPersonTargetedID
    active: true
  - id: full image url
    term: Full Image URL
    active: true
  - id: nims person id
    term: NIMS Person ID
    active: true
  - id: ORCID
    term: ORCID
    active: true
  - id: project id
    term: Project ID
    active: true
  - id: referred identifier local
    term: Referred Identifier - Local
    active: true
  - id: referred identifier persistent
    term: Referred Identifier - Persistent
    active: true
  - id: related identifier local
    term: Related Identifier - Local
    active: true
  - id: related identifier persistent
    term: Related Identifier - Persistent
    active: true
  - id: thumbnail image url
    term: Thumbnail Image URL
    active: true
  - id: web image url
    term: Web Image URL
    active: true
  - id: previous identifier
    term: Previous identifier
    active: true
