terms:
    - id: http://rightsstatements.org/vocab/InC/1.0/
      term: In Copyright
      active: true
    - id: https://creativecommons.org/licenses/by/4.0/
      term: Creative Commons BY Attribution 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-sa/4.0/
      term: Creative Commons BY-SA Attribution-ShareAlike 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nd/4.0/
      term: Creative Commons BY-ND Attribution-NoDerivatives 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc/4.0/
      term: Creative Commons BY-NC Attribution-NonCommercial 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
      term: Creative Commons BY-NC-ND Attribution-NonCommercial-NoDerivs 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
      term: Creative Commons BY-NC-SA Attribution-NonCommercial-ShareAlike 4.0 International
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: Creative Commons CC0 1.0 Universal
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Creative Commons Public Domain Mark 1.0
      active: true
    - id: http://www.apache.org/licenses/LICENSE-2.0.txt
      term: Apache License 2.0
      active: true
    - id: https://www.gnu.org/licenses/gpl.html
      term: GNU General Public License
      active: true
    - id: https://opensource.org/licenses/MIT
      term: MIT License
      active: true
