terms:
  - id: author
    term: author/著者
    active: true
  - id: editor
    term: editor/編集者
    active: true
  - id: translator
    term: translator/翻訳者
    active: true
  - id: data depositor
    term: data depositor/データ記入者
    active: true
  - id: data curator
    term: data curator/データキュレーター
    active: true
  - id: contact person
    term: non-author contact/連絡責任者（著者以外）
    active: true
  - id: operator
    term: operator/データ測定者・計算者
    active: true
