terms:
  - id: author/著者
    term: author/著者
    active: true
  - id: editor/編集者
    term: editor/編集者
    active: true
  - id: translator/翻訳者
    term: translator/翻訳者
    active: true
  - id: data depositor/データ記入者
    term: data depositor/データ記入者
    active: true
  - id: data curator/データキュレーター
    term: data curator/データキュレーター
    active: true
  - id: contact person/連絡責任者
    term: contact person/連絡責任者
    active: true
  - id: operator
    term: operator/データ測定者・計算者
    active: true
