terms:
  - id: ContactPerson
    term: Contact person
    active: true
  - id: DataCollector
    term: Data collector
    active: true
  - id: DataCurator
    term: Data curator
    active: true
  - id: DataManager
    term: Data manager
    active: true
  - id: Distributor
    term: Distributor
    active: true
  - id: Editor
    term: Editor
    active: true
  - id: HostingInstitution
    term: Hosting institution
    active: true
  - id: Producer
    term: Producer
    active: true
  - id: ProjectLeader
    term: Project leader
    active: true
  - id: ProjectManager
    term: Project manager
    active: true
  - id: ProjectMember
    term: Project member
    active: true
  - id: RegistrationAgency
    term: Registration agency
    active: true
  - id: RegistrationAuthority
    term: Registration authority
    active: true
  - id: RelatedPerson
    term: Related person
    active: true
  - id: Researcher
    term: Researcher
    active: true
  - id: ResearchGroup
    term: Research group
    active: true
  - id: RightsHolder
    term: Rights holder
    active: true
  - id: Sponsor
    term: Sponsor
    active: true
  - id: Supervisor
    term: Supervisor
    active: true
  - id: WorkPackageLeader
    term: Work package leader
    active: true
  - id: Other
    term: Other
    active: true
