source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.8'
# Use Puma as the app server
gem 'puma', '~> 4.3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Using redis to store sessions in the redis cache (rather than cookies) - this is to support single sign out
# NB: Once we upgrade to rails >= 5.2 the gem can probably be removed as redis sessions are built in
gem 'redis-session-store', '~> 0.11.1'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'factory_bot_rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'hyrax', '~> 3.6.0'
group :development, :test do
  gem 'solr_wrapper', '~> 2.0'
end

gem 'rsolr', '>= 1.0'
gem 'solrizer', '~> 4.1'
gem 'devise'
gem 'devise-guests', '~> 0.7.0'
group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3', '~> 1.3.6'
  gem 'fcrepo_wrapper'
  gem 'rspec-rails'
  gem 'pry'
end

gem 'sidekiq', '~> 5.2.10'
gem 'hydra-role-management'
gem 'bootstrap-datepicker-rails'
gem 'pg'
gem 'faraday_middleware', '~> 0.14'
gem 'devise_ldap_authenticatable'

gem 'cancancan', '~> 1.17' # NB: locked to an older version because of hyrax > hydra-editor

gem 'riiif', '~> 2.0'
gem 'jsonapi-rails', '~> 0.4.0'
gem 'faraday'
gem 'simple_form', '5.1.0'
gem 'ro-crate', '~> 0.4.11', require: 'ro_crate'
gem 'rdf-vocab', '3.1.4'

group :production do
  gem 'exception_notification', '~> 4.4'
  gem 'exception_notification-rake', '~> 0.3.1'
end

gem 'willow_sword', git: 'https://github.com/CottageLabs/willow_sword.git', :branch => 'develop'
gem 'blacklight_oai_provider', git: 'https://github.com/CottageLabs/blacklight_oai_provider.git', branch: 'oai_upgrade'

group :test do
  gem 'simplecov', require: false
  gem 'capybara'
  gem 'launchy'
  gem 'webdrivers', '~> 4.1'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'rspec-activemodel-mocks'
end

gem 'coveralls', require: false
gem 'rinku'
gem 'sitemap_generator'
gem 'cld'
# gem 'clamav-client', require: 'clamav/client'
gem 'omniauth-oauth2'
gem 'omniauth', '~> 1.9.1'
gem 'omniauth-rails_csrf_protection'
gem 'mail', '~> 2.7.1'
