default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>

development:
  <<: *default
  database: hyrax_development

test:
  <<: *default
  database: hyrax_test

production:
  <<: *default
  database: hyrax_production