default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST_APP'] || 'db' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_APP'] || 'hyrax_development' %>
  
test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] || 'hyrax_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_APP'] || 'hyrax_production' %>
  pool: 50
