port: 8080
verbose: false
version: '4.7.3' # NB: ideally this should match the version in docker-compose.yml
instance_dir: 'tmp/fcrepo4-test'
fcrepo_home_dir: 'tmp/fcrepo4-test/home'
enable_jms: false
download_dir: 'tmp'
