#config/solr_wrapper_test.yml
verbose: false
cloud: false
port: 8985
version: '7.7.2' # NB: ideally this should match the version in docker-compose.yml
download_dir: 'tmp'
instance_dir: 'tmp/solr-test'
collection:
    name: 'hydra-test'
    dir: 'solr/config'
    persist: false
