apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mdr-fcrepo
  name: mdr-fcrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdr-fcrepo
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: mdr-fcrepo
    spec:
      containers:
      - name: mdr-fcrepo
        image: ualbertalib/docker-fcrepo4:4.7
        envFrom:
          - secretRef:
              name: pg-secrets
        env:
          - name: CATALINA_OPTS
            value: -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC -Dfcrepo.home=/data -Dfcrepo.object.directory=/data/objects -Dfcrepo.binary.directory=/data/binaries -Dfcrepo.postgresql.username=$POSTGRES_USER -Dfcrepo.postgresql.password=$POSTGRES_PASSWORD -Dfcrepo.postgresql.host=$POSTGRES_HOST_FCREPO -Dfcrepo.postgresql.port=$POSTGRES_PORT -Dfcrepo.modeshape.configuration=https://raw.githubusercontent.com/nims-dpfc/nims-hyrax/azure-saas/k8s_deployment/fcrepo_repository.json
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: fcrepo
          mountPath: /data
      volumes:
      - name: fcrepo
        persistentVolumeClaim:
          claimName: fcrepo
      hostname: mdr-fcrepo
      # restartPolicy: Always
