apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mdr-web
  name: mdr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdr-web
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: mdr-web
    spec:
      containers:
      - name: mdr-web
#        image: docker.io/library/nims-hyrax_web:latest
        image: nims-hyrax_web:latest
        imagePullPolicy: IfNotPresent
        args:
          - bash
          - -c
          - /bin/docker-entrypoint.sh
        envFrom:
        - configMapRef:
            name: nims-hyrax-config
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: web-file-uploads
            mountPath: /shared/uploads/
          - name: web-derivatives
            mountPath: /shared/derivatives/
          - name: web-cache
            mountPath: /shared/cache/
          - name: web-branding
            mountPath: /data/public/branding
#          - name: web-data-data
#            mountPath: /data/data
#          - name: web-data
#            mountPath: /data
      volumes:
        - name: web-file-uploads
          persistentVolumeClaim:
            claimName: web-file-uploads
        - name: web-derivatives
          persistentVolumeClaim:
            claimName: web-derivatives
        - name: web-cache
          persistentVolumeClaim:
            claimName: web-cache
        - name: web-branding
          persistentVolumeClaim:
            claimName: web-branding
#        - name: web-data-data
#          persistentVolumeClaim:
#            claimName: web-data-data
#        - name: web-data
#          persistentVolumeClaim:
#            claimName: web-data
      hostname: mdr-web
      # restartPolicy: Always
