apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mdr-web
  name: mdr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdr-web
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: mdr-web
    spec:
      initContainers:
      - name: solr-startup
        image: alpine/git
        envFrom:
        - configMapRef:
            name: nims-hyrax-config
        command:
          - /bin/sh
          - -c
          - "wget http://${SOLR_HOST}:${SOLR_PORT}/solr/admin/info/system"
      - name: fedora-startup
        image: alpine/git
        envFrom:
          - configMapRef:
              name: nims-hyrax-config
        command:
          - /bin/sh
          - -c
          - "wget http://${FEDORA_HOST}:${FEDORA_PORT}/fcrepo/rest"
      containers:
      - name: mdr-web
        image: nims-hyrax_web:latest
        imagePullPolicy: IfNotPresent
        args:
          - bash
          - -c
          - /bin/docker-entrypoint.sh
        envFrom:
        - configMapRef:
            name: nims-hyrax-config
        env:
        - name: AZURE_APP_ID
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_APP_ID
        - name: AZURE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_APP_SECRET
        - name: AZURE_SCOPES
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_SCOPES
        - name: AZURE_OAUTH_SITE_URL
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_OAUTH_SITE_URL
        - name: AZURE_OAUTH_AUTHORIZE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_OAUTH_AUTHORIZE_ENDPOINT
        - name: AZURE_OAUTH_TOKEN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-auth-secrets
              key: AZURE_OAUTH_TOKEN_ENDPOINT
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: web-file-uploads
            mountPath: /shared/uploads/
          - name: web-derivatives
            mountPath: /shared/derivatives/
          - name: web-cache
            mountPath: /shared/cache/
          - name: web-branding
            mountPath: /data/public/branding
      volumes:
        - name: web-file-uploads
          persistentVolumeClaim:
            claimName: web-file-uploads
        - name: web-derivatives
          persistentVolumeClaim:
            claimName: web-derivatives
        - name: web-cache
          persistentVolumeClaim:
            claimName: web-cache
        - name: web-branding
          persistentVolumeClaim:
            claimName: web-branding
      hostname: mdr-web
      # restartPolicy: Always
