module RDF
  module Vocab
    class NimsRdp < RDF::Vocabulary("http://www.nims.go.jp/vocabs/ngdr/")
      property 'CustomProperty'
      property 'Instrument'
      property 'PurchaseRecord'
      property 'Specimen'
      property 'characterization-methods'
      property 'chemical-composition'
      property 'computational-methods'
      property 'crystallographic-structure'
      property 'custom-property'
      property 'data-origin'
      property 'identifier'
      property 'instrument'
      property 'instrument-date'
      property 'instrument-function-tier1'
      property 'instrument-function-tier2'
      property 'instrument-manufacturer'
      property 'instrument-operator'
      property 'instrument-organization'
      property 'instrument-title'
      property 'material-types'
      property 'origin-system-provenance'
      property 'properties-addressed'
      property 'purchase-record'
      property 'purchase-record-date'
      property 'purchase-record-identifier'
      property 'purchase-record-item'
      property 'purchase-record-title'
      property 'specimen-set'
      property 'specimen-title'
      property 'specimen-type'
      property 'structural-features'
      property 'synthesis-and-processing'
      property 'version'
      property 'version-date'
      property 'version-identifier'
    end
  end
end
