# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base

  property :date_copyrighted, predicate: ::RDF::Vocab::DC.dateCopyrighted do |index|
    index.as :stored_searchable, type: :date
  end

  include ::Hyrax::FileSetBehavior
end
