# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :date_copyrighted, predicate: ::RDF::Vocab::DC.dateCopyrighted do |index|
    index.as :stored_searchable, type: :date
  end

  include ::Hyrax::FileSetBehavior

  # override method in lib/hydra/works/models/concerns/file_set/mime_types.rb
  #   add text/plain
  def self.office_document_mime_types
    [
      'text/plain',
      'text/csv',
      'text/tab-separated-values',
      'text/rtf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.oasis.opendocument.text',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    ]
  end

  def text?
    ['text/plain',
     'text/csv',
     'text/tab-separated-values'].include? mime_type
  end
end
