# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  property :date_copyrighted, predicate: ::RDF::Vocab::DC.dateCopyrighted , multiple: false do |index|
    index.as :stored_searchable, type: :date
  end

  property :format, predicate: ::RDF::Vocab::DC.format , multiple: false do |index|
    index.as :stored_searchable, :symbol
  end

  property :extent, predicate: ::RDF::Vocab::DC.extent , multiple: false do |index|
    index.as :stored_searchable
  end
end
